<?php

/**
 * BaseLimelightScore
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $amount
 * @property integer $item_id
 * @property enum $type
 * @property enum $status
 * @property integer $contributing_item_id
 * @property integer $user_id
 * @property Limelight $Item
 * 
 * @method integer        getId()                   Returns the current record's "id" value
 * @method integer        getAmount()               Returns the current record's "amount" value
 * @method integer        getItemId()               Returns the current record's "item_id" value
 * @method enum           getType()                 Returns the current record's "type" value
 * @method enum           getStatus()               Returns the current record's "status" value
 * @method integer        getContributingItemId()   Returns the current record's "contributing_item_id" value
 * @method integer        getUserId()               Returns the current record's "user_id" value
 * @method Limelight      getItem()                 Returns the current record's "Item" value
 * @method LimelightScore setId()                   Sets the current record's "id" value
 * @method LimelightScore setAmount()               Sets the current record's "amount" value
 * @method LimelightScore setItemId()               Sets the current record's "item_id" value
 * @method LimelightScore setType()                 Sets the current record's "type" value
 * @method LimelightScore setStatus()               Sets the current record's "status" value
 * @method LimelightScore setContributingItemId()   Sets the current record's "contributing_item_id" value
 * @method LimelightScore setUserId()               Sets the current record's "user_id" value
 * @method LimelightScore setItem()                 Sets the current record's "Item" value
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLimelightScore extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('limelight_score');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('amount', 'integer', 3, array(
             'type' => 'integer',
             'default' => 1,
             'length' => 3,
             ));
        $this->hasColumn('item_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'News',
              1 => 'Wiki',
              2 => 'LimelightReviewUser',
              3 => 'LimelightReviewPro',
              4 => 'LimelightProCon',
              5 => 'LimelightSpecification',
             ),
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Flagged',
              1 => 'Struck',
              2 => 'Disabled',
              3 => 'Active',
             ),
             'default' => 'Active',
             ));
        $this->hasColumn('contributing_item_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));


        $this->index('limelightIndex', array(
             'fields' => 
             array(
              0 => 'item_id',
             ),
             ));
        $this->index('userIndex', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Limelight as Item', array(
             'local' => 'item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}