<?php

/**
 * BaseLimelightScores
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $count
 * @property integer $limelight_id
 * @property integer $user_id
 * @property integer $target_user_id
 * @property enum $score_type
 * @property Limelight $Limelight
 * 
 * @method integer         getCount()          Returns the current record's "count" value
 * @method integer         getLimelightId()    Returns the current record's "limelight_id" value
 * @method integer         getUserId()         Returns the current record's "user_id" value
 * @method integer         getTargetUserId()   Returns the current record's "target_user_id" value
 * @method enum            getScoreType()      Returns the current record's "score_type" value
 * @method Limelight       getLimelight()      Returns the current record's "Limelight" value
 * @method LimelightScores setCount()          Sets the current record's "count" value
 * @method LimelightScores setLimelightId()    Sets the current record's "limelight_id" value
 * @method LimelightScores setUserId()         Sets the current record's "user_id" value
 * @method LimelightScores setTargetUserId()   Sets the current record's "target_user_id" value
 * @method LimelightScores setScoreType()      Sets the current record's "score_type" value
 * @method LimelightScores setLimelight()      Sets the current record's "Limelight" value
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseLimelightScores extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('limelight_scores');
        $this->hasColumn('count', 'integer', 3, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '3',
             ));
        $this->hasColumn('limelight_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('target_user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('score_type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'News',
             ),
             ));


        $this->index('index', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Limelight', array(
             'local' => 'limelight_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}