<?php

/**
 * BaseCategorySpecification
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $category_id
 * @property integer $specification_id
 * @property enum $status
 * @property Category $Category
 * @property Specification $Specification
 * 
 * @method integer               getId()               Returns the current record's "id" value
 * @method integer               getCategoryId()       Returns the current record's "category_id" value
 * @method integer               getSpecificationId()  Returns the current record's "specification_id" value
 * @method enum                  getStatus()           Returns the current record's "status" value
 * @method Category              getCategory()         Returns the current record's "Category" value
 * @method Specification         getSpecification()    Returns the current record's "Specification" value
 * @method CategorySpecification setId()               Sets the current record's "id" value
 * @method CategorySpecification setCategoryId()       Sets the current record's "category_id" value
 * @method CategorySpecification setSpecificationId()  Sets the current record's "specification_id" value
 * @method CategorySpecification setStatus()           Sets the current record's "status" value
 * @method CategorySpecification setCategory()         Sets the current record's "Category" value
 * @method CategorySpecification setSpecification()    Sets the current record's "Specification" value
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategorySpecification extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category_specification');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('specification_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Active',
              1 => 'Pending',
              2 => 'Struck',
              3 => 'Flagged',
              4 => 'Disabled',
             ),
             'default' => 'Active',
             ));


        $this->index('categoryIndex', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Specification', array(
             'local' => 'specification_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}