<?php

/**
 * BaseFollowLimelightReference
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $limelight_id
 * 
 * @method integer                  getUserId()       Returns the current record's "user_id" value
 * @method integer                  getLimelightId()  Returns the current record's "limelight_id" value
 * @method FollowLimelightReference setUserId()       Sets the current record's "user_id" value
 * @method FollowLimelightReference setLimelightId()  Sets the current record's "limelight_id" value
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFollowLimelightReference extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('follow_limelight_reference');
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('limelight_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}