<?php

/**
 * BaseLimelightOwn
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $item_id
 * @property integer $user_id
 * @property sfGuardUser $User
 * @property Limelight $Item
 * 
 * @method integer      getItemId()  Returns the current record's "item_id" value
 * @method integer      getUserId()  Returns the current record's "user_id" value
 * @method sfGuardUser  getUser()    Returns the current record's "User" value
 * @method Limelight    getItem()    Returns the current record's "Item" value
 * @method LimelightOwn setItemId()  Sets the current record's "item_id" value
 * @method LimelightOwn setUserId()  Sets the current record's "user_id" value
 * @method LimelightOwn setUser()    Sets the current record's "User" value
 * @method LimelightOwn setItem()    Sets the current record's "Item" value
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLimelightOwn extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('limelight_own');
        $this->hasColumn('item_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Limelight as Item', array(
             'local' => 'item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}