<?php

/**
 * BaseCategoryNews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $news_id
 * @property integer $category_id
 * @property News $News
 * @property Category $Category
 * 
 * @method integer      getNewsId()      Returns the current record's "news_id" value
 * @method integer      getCategoryId()  Returns the current record's "category_id" value
 * @method News         getNews()        Returns the current record's "News" value
 * @method Category     getCategory()    Returns the current record's "Category" value
 * @method CategoryNews setNewsId()      Sets the current record's "news_id" value
 * @method CategoryNews setCategoryId()  Sets the current record's "category_id" value
 * @method CategoryNews setNews()        Sets the current record's "News" value
 * @method CategoryNews setCategory()    Sets the current record's "Category" value
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoryNews extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category_news');
        $this->hasColumn('news_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('News', array(
             'local' => 'news_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}