<?php

/**
 * BaseUserReviewFavorite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property sfGuardUser $User
 * 
 * @method sfGuardUser        getUser() Returns the current record's "User" value
 * @method UserReviewFavorite setUser() Sets the current record's "User" value
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserReviewFavorite extends Favorite
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('user_review_favorite');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}