<?php

/**
 * BaseLimelightProCon
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $score
 * @property enum $type
 * @property integer $item_id
 * @property integer $user_id
 * @property sfGuardUser $User
 * @property Limelight $Item
 * @property Doctrine_Collection $UserAction
 * @property Doctrine_Collection $Scores
 * @property Doctrine_Collection $Flags
 * 
 * @method string              getName()       Returns the current record's "name" value
 * @method integer             getScore()      Returns the current record's "score" value
 * @method enum                getType()       Returns the current record's "type" value
 * @method integer             getItemId()     Returns the current record's "item_id" value
 * @method integer             getUserId()     Returns the current record's "user_id" value
 * @method sfGuardUser         getUser()       Returns the current record's "User" value
 * @method Limelight           getItem()       Returns the current record's "Item" value
 * @method Doctrine_Collection getUserAction() Returns the current record's "UserAction" collection
 * @method Doctrine_Collection getScores()     Returns the current record's "Scores" collection
 * @method Doctrine_Collection getFlags()      Returns the current record's "Flags" collection
 * @method LimelightProCon     setName()       Sets the current record's "name" value
 * @method LimelightProCon     setScore()      Sets the current record's "score" value
 * @method LimelightProCon     setType()       Sets the current record's "type" value
 * @method LimelightProCon     setItemId()     Sets the current record's "item_id" value
 * @method LimelightProCon     setUserId()     Sets the current record's "user_id" value
 * @method LimelightProCon     setUser()       Sets the current record's "User" value
 * @method LimelightProCon     setItem()       Sets the current record's "Item" value
 * @method LimelightProCon     setUserAction() Sets the current record's "UserAction" collection
 * @method LimelightProCon     setScores()     Sets the current record's "Scores" collection
 * @method LimelightProCon     setFlags()      Sets the current record's "Flags" collection
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLimelightProCon extends Item
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('limelight_pro_con');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('score', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'pro',
              1 => 'con',
             ),
             ));
        $this->hasColumn('item_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));


        $this->index('itemIndex', array(
             'fields' => 
             array(
              0 => 'item_id',
             ),
             ));
        $this->index('userIndex', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Limelight as Item', array(
             'local' => 'item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('UserAction', array(
             'local' => 'id',
             'foreign' => 'LimelightProCon_id'));

        $this->hasMany('LimelightProConScore as Scores', array(
             'local' => 'id',
             'foreign' => 'item_id'));

        $this->hasMany('LimelightProConFlag as Flags', array(
             'local' => 'id',
             'foreign' => 'item_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'name' => 'name_slug',
             ));
        $this->actAs($sluggable0);
    }
}