<?php

/**
 * BaseLink
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $source_name
 * @property string $source_url
 * @property integer $count
 * @property integer $score
 * @property integer $item_id
 * @property integer $link_id
 * @property sfGuardUser $User
 * @property Doctrine_Collection $NewsLinks
 * 
 * @method string              getSourceName()  Returns the current record's "source_name" value
 * @method string              getSourceUrl()   Returns the current record's "source_url" value
 * @method integer             getCount()       Returns the current record's "count" value
 * @method integer             getScore()       Returns the current record's "score" value
 * @method integer             getItemId()      Returns the current record's "item_id" value
 * @method integer             getLinkId()      Returns the current record's "link_id" value
 * @method sfGuardUser         getUser()        Returns the current record's "User" value
 * @method Doctrine_Collection getNewsLinks()   Returns the current record's "NewsLinks" collection
 * @method Link                setSourceName()  Sets the current record's "source_name" value
 * @method Link                setSourceUrl()   Sets the current record's "source_url" value
 * @method Link                setCount()       Sets the current record's "count" value
 * @method Link                setScore()       Sets the current record's "score" value
 * @method Link                setItemId()      Sets the current record's "item_id" value
 * @method Link                setLinkId()      Sets the current record's "link_id" value
 * @method Link                setUser()        Sets the current record's "User" value
 * @method Link                setNewsLinks()   Sets the current record's "NewsLinks" collection
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLink extends Item
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('link');
        $this->hasColumn('source_name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('source_url', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('count', 'integer', null, array(
             'type' => 'integer',
             'default' => 1,
             ));
        $this->hasColumn('score', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('item_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('link_id', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('itemIndex', array(
             'fields' => 
             array(
              0 => 'item_id',
             ),
             ));
        $this->index('linkIndex', array(
             'fields' => 
             array(
              0 => 'link_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('NewsLink as NewsLinks', array(
             'local' => 'id',
             'foreign' => 'link_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'source_name',
             ),
             'name' => 'source_name_slug',
             ));
        $this->actAs($sluggable0);
    }
}