<?php

/**
 * BaseLimelightReviewScoreParts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_score_type_id
 * @property integer $review_id
 * @property integer $score
 * @property CategoryScoreType $CategoryScoreType
 * @property LimelightReviewUser $LimelightReviewUser
 * 
 * @method integer                   getCategoryScoreTypeId()    Returns the current record's "category_score_type_id" value
 * @method integer                   getReviewId()               Returns the current record's "review_id" value
 * @method integer                   getScore()                  Returns the current record's "score" value
 * @method CategoryScoreType         getCategoryScoreType()      Returns the current record's "CategoryScoreType" value
 * @method LimelightReviewUser       getLimelightReviewUser()    Returns the current record's "LimelightReviewUser" value
 * @method LimelightReviewScoreParts setCategoryScoreTypeId()    Sets the current record's "category_score_type_id" value
 * @method LimelightReviewScoreParts setReviewId()               Sets the current record's "review_id" value
 * @method LimelightReviewScoreParts setScore()                  Sets the current record's "score" value
 * @method LimelightReviewScoreParts setCategoryScoreType()      Sets the current record's "CategoryScoreType" value
 * @method LimelightReviewScoreParts setLimelightReviewUser()    Sets the current record's "LimelightReviewUser" value
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseLimelightReviewScoreParts extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('limelight_review_score_parts');
        $this->hasColumn('category_score_type_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('review_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('score', 'integer', 2, array(
             'type' => 'integer',
             'length' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CategoryScoreType', array(
             'local' => 'category_score_type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('LimelightReviewUser', array(
             'local' => 'review_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}