<?php

/**
 * BaseLimelightProConFlags
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $limelightprocon_id
 * @property enum $flag_type
 * @property integer $user_id
 * @property sfGuardUser $User
 * @property LimelightProCon $LimelightProCon
 * 
 * @method integer              getLimelightproconId()  Returns the current record's "limelightprocon_id" value
 * @method enum                 getFlagType()           Returns the current record's "flag_type" value
 * @method integer              getUserId()             Returns the current record's "user_id" value
 * @method sfGuardUser          getUser()               Returns the current record's "User" value
 * @method LimelightProCon      getLimelightProCon()    Returns the current record's "LimelightProCon" value
 * @method LimelightProConFlags setLimelightproconId()  Sets the current record's "limelightprocon_id" value
 * @method LimelightProConFlags setFlagType()           Sets the current record's "flag_type" value
 * @method LimelightProConFlags setUserId()             Sets the current record's "user_id" value
 * @method LimelightProConFlags setUser()               Sets the current record's "User" value
 * @method LimelightProConFlags setLimelightProCon()    Sets the current record's "LimelightProCon" value
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseLimelightProConFlags extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('limelight_pro_con_flags');
        $this->hasColumn('limelightprocon_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('flag_type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Duplicate',
              1 => 'Inappropriate',
              2 => 'Spam',
              3 => 'Other',
             ),
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('LimelightProCon', array(
             'local' => 'limelightprocon_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}