<?php

/**
 * BaseSong
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $content
 * @property string $song_image
 * @property integer $score
 * @property integer $total_plays
 * @property integer $favorited_count
 * @property integer $favorite_badge_flag
 * @property integer $tag_lock
 * @property integer $comment_lock
 * @property integer $user_id
 * @property sfGuardUser $User
 * @property Doctrine_Collection $Limelights
 * @property Doctrine_Collection $SongLimelights
 * @property Doctrine_Collection $Comments
 * @property Doctrine_Collection $Favorited
 * @property Doctrine_Collection $Plays
 * @property Doctrine_Collection $Scores
 * @property Doctrine_Collection $Flags
 * 
 * @method string              getName()                Returns the current record's "name" value
 * @method string              getContent()             Returns the current record's "content" value
 * @method string              getSongImage()           Returns the current record's "song_image" value
 * @method integer             getScore()               Returns the current record's "score" value
 * @method integer             getTotalPlays()          Returns the current record's "total_plays" value
 * @method integer             getFavoritedCount()      Returns the current record's "favorited_count" value
 * @method integer             getFavoriteBadgeFlag()   Returns the current record's "favorite_badge_flag" value
 * @method integer             getTagLock()             Returns the current record's "tag_lock" value
 * @method integer             getCommentLock()         Returns the current record's "comment_lock" value
 * @method integer             getUserId()              Returns the current record's "user_id" value
 * @method sfGuardUser         getUser()                Returns the current record's "User" value
 * @method Doctrine_Collection getLimelights()          Returns the current record's "Limelights" collection
 * @method Doctrine_Collection getSongLimelights()      Returns the current record's "SongLimelights" collection
 * @method Doctrine_Collection getComments()            Returns the current record's "Comments" collection
 * @method Doctrine_Collection getFavorited()           Returns the current record's "Favorited" collection
 * @method Doctrine_Collection getPlays()               Returns the current record's "Plays" collection
 * @method Doctrine_Collection getScores()              Returns the current record's "Scores" collection
 * @method Doctrine_Collection getFlags()               Returns the current record's "Flags" collection
 * @method Song                setName()                Sets the current record's "name" value
 * @method Song                setContent()             Sets the current record's "content" value
 * @method Song                setSongImage()           Sets the current record's "song_image" value
 * @method Song                setScore()               Sets the current record's "score" value
 * @method Song                setTotalPlays()          Sets the current record's "total_plays" value
 * @method Song                setFavoritedCount()      Sets the current record's "favorited_count" value
 * @method Song                setFavoriteBadgeFlag()   Sets the current record's "favorite_badge_flag" value
 * @method Song                setTagLock()             Sets the current record's "tag_lock" value
 * @method Song                setCommentLock()         Sets the current record's "comment_lock" value
 * @method Song                setUserId()              Sets the current record's "user_id" value
 * @method Song                setUser()                Sets the current record's "User" value
 * @method Song                setLimelights()          Sets the current record's "Limelights" collection
 * @method Song                setSongLimelights()      Sets the current record's "SongLimelights" collection
 * @method Song                setComments()            Sets the current record's "Comments" collection
 * @method Song                setFavorited()           Sets the current record's "Favorited" collection
 * @method Song                setPlays()               Sets the current record's "Plays" collection
 * @method Song                setScores()              Sets the current record's "Scores" collection
 * @method Song                setFlags()               Sets the current record's "Flags" collection
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSong extends Item
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('song');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('content', 'string', 2000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 2000,
             ));
        $this->hasColumn('song_image', 'string', 255, array(
             'type' => 'string',
             'default' => 'news_profile_default.gif',
             'length' => 255,
             ));
        $this->hasColumn('score', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('total_plays', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('favorited_count', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('favorite_badge_flag', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('tag_lock', 'integer', 3, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 3,
             ));
        $this->hasColumn('comment_lock', 'integer', 3, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 3,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));


        $this->index('index', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Limelight as Limelights', array(
             'refClass' => 'LimelightSong',
             'local' => 'song_id',
             'foreign' => 'limelight_id'));

        $this->hasMany('LimelightSong as SongLimelights', array(
             'local' => 'id',
             'foreign' => 'song_id'));

        $this->hasMany('Comment as Comments', array(
             'local' => 'id',
             'foreign' => 'Song_id'));

        $this->hasMany('SongFavorite as Favorited', array(
             'local' => 'id',
             'foreign' => 'item_id'));

        $this->hasMany('SongPlay as Plays', array(
             'local' => 'id',
             'foreign' => 'item_id'));

        $this->hasMany('SongScore as Scores', array(
             'local' => 'id',
             'foreign' => 'item_id'));

        $this->hasMany('SongFlag as Flags', array(
             'local' => 'id',
             'foreign' => 'item_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             'name' => 'name_slug',
             ));
        $this->actAs($sluggable0);
    }
}