<?php

/**
 * BaseLimelightReviewScorePart
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $category_score_type_id
 * @property integer $review_id
 * @property integer $score
 * @property CategoryScoreType $CategoryScoreType
 * @property LimelightReviewUser $LimelightReviewUser
 * 
 * @method integer                  getId()                     Returns the current record's "id" value
 * @method integer                  getCategoryScoreTypeId()    Returns the current record's "category_score_type_id" value
 * @method integer                  getReviewId()               Returns the current record's "review_id" value
 * @method integer                  getScore()                  Returns the current record's "score" value
 * @method CategoryScoreType        getCategoryScoreType()      Returns the current record's "CategoryScoreType" value
 * @method LimelightReviewUser      getLimelightReviewUser()    Returns the current record's "LimelightReviewUser" value
 * @method LimelightReviewScorePart setId()                     Sets the current record's "id" value
 * @method LimelightReviewScorePart setCategoryScoreTypeId()    Sets the current record's "category_score_type_id" value
 * @method LimelightReviewScorePart setReviewId()               Sets the current record's "review_id" value
 * @method LimelightReviewScorePart setScore()                  Sets the current record's "score" value
 * @method LimelightReviewScorePart setCategoryScoreType()      Sets the current record's "CategoryScoreType" value
 * @method LimelightReviewScorePart setLimelightReviewUser()    Sets the current record's "LimelightReviewUser" value
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLimelightReviewScorePart extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('limelight_review_score_part');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('category_score_type_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('review_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('score', 'integer', 3, array(
             'type' => 'integer',
             'length' => 3,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CategoryScoreType', array(
             'local' => 'category_score_type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('LimelightReviewUser', array(
             'local' => 'review_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}