<?php

/**
 * BaseNewsFlags
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $news_id
 * @property enum $flag_type
 * @property integer $user_id
 * @property sfGuardUser $User
 * @property News $News
 * 
 * @method integer     getNewsId()    Returns the current record's "news_id" value
 * @method enum        getFlagType()  Returns the current record's "flag_type" value
 * @method integer     getUserId()    Returns the current record's "user_id" value
 * @method sfGuardUser getUser()      Returns the current record's "User" value
 * @method News        getNews()      Returns the current record's "News" value
 * @method NewsFlags   setNewsId()    Sets the current record's "news_id" value
 * @method NewsFlags   setFlagType()  Sets the current record's "flag_type" value
 * @method NewsFlags   setUserId()    Sets the current record's "user_id" value
 * @method NewsFlags   setUser()      Sets the current record's "User" value
 * @method NewsFlags   setNews()      Sets the current record's "News" value
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseNewsFlags extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('news_flags');
        $this->hasColumn('news_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('flag_type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Duplicate',
              1 => 'Inappropriate',
              2 => 'Other',
             ),
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('News', array(
             'local' => 'news_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}