<?php

/**
 * BaseLimelightSong
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $limelight_id
 * @property integer $song_id
 * @property Limelight $Limelight
 * @property Song $Song
 * 
 * @method integer       getLimelightId()  Returns the current record's "limelight_id" value
 * @method integer       getSongId()       Returns the current record's "song_id" value
 * @method Limelight     getLimelight()    Returns the current record's "Limelight" value
 * @method Song          getSong()         Returns the current record's "Song" value
 * @method LimelightSong setLimelightId()  Sets the current record's "limelight_id" value
 * @method LimelightSong setSongId()       Sets the current record's "song_id" value
 * @method LimelightSong setLimelight()    Sets the current record's "Limelight" value
 * @method LimelightSong setSong()         Sets the current record's "Song" value
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLimelightSong extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('limelight_song');
        $this->hasColumn('limelight_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('song_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Limelight', array(
             'local' => 'limelight_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Song', array(
             'local' => 'song_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}