<?php

/**
 * BaseLimelightReviewUserFlags
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $review_id
 * @property enum $flag_type
 * @property integer $user_id
 * @property sfGuardUser $User
 * @property LimelightReviewUser $LimelightReviewUser
 * 
 * @method integer                  getReviewId()            Returns the current record's "review_id" value
 * @method enum                     getFlagType()            Returns the current record's "flag_type" value
 * @method integer                  getUserId()              Returns the current record's "user_id" value
 * @method sfGuardUser              getUser()                Returns the current record's "User" value
 * @method LimelightReviewUser      getLimelightReviewUser() Returns the current record's "LimelightReviewUser" value
 * @method LimelightReviewUserFlags setReviewId()            Sets the current record's "review_id" value
 * @method LimelightReviewUserFlags setFlagType()            Sets the current record's "flag_type" value
 * @method LimelightReviewUserFlags setUserId()              Sets the current record's "user_id" value
 * @method LimelightReviewUserFlags setUser()                Sets the current record's "User" value
 * @method LimelightReviewUserFlags setLimelightReviewUser() Sets the current record's "LimelightReviewUser" value
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseLimelightReviewUserFlags extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('limelight_review_user_flags');
        $this->hasColumn('review_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('flag_type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Duplicate',
              1 => 'Spam',
              2 => 'Innapropriate',
              3 => 'Other',
             ),
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('LimelightReviewUser', array(
             'local' => 'review_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}