<?php

/**
 * BaseSongScore
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Song $Item
 * 
 * @method Song      getItem() Returns the current record's "Item" value
 * @method SongScore setItem() Sets the current record's "Item" value
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSongScore extends Score
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('song_score');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Song as Item', array(
             'local' => 'item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}