<?php

/**
 * BaseNewsView
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $item_id
 * @property News $Item
 * 
 * @method integer  getItemId()  Returns the current record's "item_id" value
 * @method News     getItem()    Returns the current record's "Item" value
 * @method NewsView setItemId()  Sets the current record's "item_id" value
 * @method NewsView setItem()    Sets the current record's "Item" value
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNewsView extends View
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('news_view');
        $this->hasColumn('item_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));


        $this->index('newsIndex', array(
             'fields' => 
             array(
              0 => 'item_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('News as Item', array(
             'local' => 'item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}