<?php

/**
 * BaseBetaEmail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $email
 * @property string $ip
 * 
 * @method string    getEmail() Returns the current record's "email" value
 * @method string    getIp()    Returns the current record's "ip" value
 * @method BetaEmail setEmail() Sets the current record's "email" value
 * @method BetaEmail setIp()    Sets the current record's "ip" value
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBetaEmail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('beta_email');
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'email' => true,
             'length' => 255,
             ));
        $this->hasColumn('ip', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}