<?php

/**
 * BaseLimelightCoreSpec
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property enum $name
 * @property string $content
 * @property integer $limelight_id
 * @property sfGuardUser $User
 * @property Limelight $Limelight
 * 
 * @method enum              getName()         Returns the current record's "name" value
 * @method string            getContent()      Returns the current record's "content" value
 * @method integer           getLimelightId()  Returns the current record's "limelight_id" value
 * @method sfGuardUser       getUser()         Returns the current record's "User" value
 * @method Limelight         getLimelight()    Returns the current record's "Limelight" value
 * @method LimelightCoreSpec setName()         Sets the current record's "name" value
 * @method LimelightCoreSpec setContent()      Sets the current record's "content" value
 * @method LimelightCoreSpec setLimelightId()  Sets the current record's "limelight_id" value
 * @method LimelightCoreSpec setUser()         Sets the current record's "User" value
 * @method LimelightCoreSpec setLimelight()    Sets the current record's "Limelight" value
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLimelightCoreSpec extends Item
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('limelight_core_spec');
        $this->hasColumn('name', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Manufacturer',
              1 => 'Release Date',
              2 => 'MSRP',
             ),
             ));
        $this->hasColumn('content', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('limelight_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Limelight', array(
             'local' => 'limelight_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}