<?php

/**
 * BaseNewsLink
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $source_url
 * @property integer $score
 * @property integer $item_id
 * @property integer $source_id
 * @property sfGuardUser $User
 * @property Limelight $Source
 * @property News $Item
 * @property Doctrine_Collection $Scores
 * @property Doctrine_Collection $Flags
 * 
 * @method string              getSourceUrl()  Returns the current record's "source_url" value
 * @method integer             getScore()      Returns the current record's "score" value
 * @method integer             getItemId()     Returns the current record's "item_id" value
 * @method integer             getSourceId()   Returns the current record's "source_id" value
 * @method sfGuardUser         getUser()       Returns the current record's "User" value
 * @method Limelight           getSource()     Returns the current record's "Source" value
 * @method News                getItem()       Returns the current record's "Item" value
 * @method Doctrine_Collection getScores()     Returns the current record's "Scores" collection
 * @method Doctrine_Collection getFlags()      Returns the current record's "Flags" collection
 * @method NewsLink            setSourceUrl()  Sets the current record's "source_url" value
 * @method NewsLink            setScore()      Sets the current record's "score" value
 * @method NewsLink            setItemId()     Sets the current record's "item_id" value
 * @method NewsLink            setSourceId()   Sets the current record's "source_id" value
 * @method NewsLink            setUser()       Sets the current record's "User" value
 * @method NewsLink            setSource()     Sets the current record's "Source" value
 * @method NewsLink            setItem()       Sets the current record's "Item" value
 * @method NewsLink            setScores()     Sets the current record's "Scores" collection
 * @method NewsLink            setFlags()      Sets the current record's "Flags" collection
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNewsLink extends Item
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('news_link');
        $this->hasColumn('source_url', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('score', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('item_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('source_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Limelight as Source', array(
             'local' => 'source_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('News as Item', array(
             'local' => 'item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('NewsLinkScore as Scores', array(
             'local' => 'id',
             'foreign' => 'item_id'));

        $this->hasMany('NewsLinkFlag as Flags', array(
             'local' => 'id',
             'foreign' => 'item_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'source_url',
             ),
             'name' => 'source_url_slug',
             ));
        $this->actAs($sluggable0);
    }
}