<?php

/**
 * BaseCommentScores
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $count
 * @property integer $comment_id
 * @property integer $user_id
 * @property integer $target_user_id
 * @property Comment $Comment
 * 
 * @method integer       getCount()          Returns the current record's "count" value
 * @method integer       getCommentId()      Returns the current record's "comment_id" value
 * @method integer       getUserId()         Returns the current record's "user_id" value
 * @method integer       getTargetUserId()   Returns the current record's "target_user_id" value
 * @method Comment       getComment()        Returns the current record's "Comment" value
 * @method CommentScores setCount()          Sets the current record's "count" value
 * @method CommentScores setCommentId()      Sets the current record's "comment_id" value
 * @method CommentScores setUserId()         Sets the current record's "user_id" value
 * @method CommentScores setTargetUserId()   Sets the current record's "target_user_id" value
 * @method CommentScores setComment()        Sets the current record's "Comment" value
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCommentScores extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comment_scores');
        $this->hasColumn('count', 'integer', 3, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '3',
             ));
        $this->hasColumn('comment_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('target_user_id', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('index', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Comment', array(
             'local' => 'comment_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}