<?php

/**
 * BaseFavorite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $item_id
 * @property sfGuardUser $User
 * 
 * @method integer     getId()      Returns the current record's "id" value
 * @method integer     getUserId()  Returns the current record's "user_id" value
 * @method integer     getItemId()  Returns the current record's "item_id" value
 * @method sfGuardUser getUser()    Returns the current record's "User" value
 * @method Favorite    setId()      Sets the current record's "id" value
 * @method Favorite    setUserId()  Sets the current record's "user_id" value
 * @method Favorite    setItemId()  Sets the current record's "item_id" value
 * @method Favorite    setUser()    Sets the current record's "User" value
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFavorite extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('favorite');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('item_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));


        $this->index('userIndex', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->index('itemIndex', array(
             'fields' => 
             array(
              0 => 'item_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}