<?php

/**
 * BaseUserNotification
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $message
 * @property enum $type
 * @property integer $is_read
 * @property integer $user_id
 * @property sfGuardUser $User
 * 
 * @method integer          getId()      Returns the current record's "id" value
 * @method string           getMessage() Returns the current record's "message" value
 * @method enum             getType()    Returns the current record's "type" value
 * @method integer          getIsRead()  Returns the current record's "is_read" value
 * @method integer          getUserId()  Returns the current record's "user_id" value
 * @method sfGuardUser      getUser()    Returns the current record's "User" value
 * @method UserNotification setId()      Sets the current record's "id" value
 * @method UserNotification setMessage() Sets the current record's "message" value
 * @method UserNotification setType()    Sets the current record's "type" value
 * @method UserNotification setIsRead()  Sets the current record's "is_read" value
 * @method UserNotification setUserId()  Sets the current record's "user_id" value
 * @method UserNotification setUser()    Sets the current record's "User" value
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserNotification extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_notification');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('message', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'misc',
              1 => 'badge',
              2 => 'moderator',
             ),
             ));
        $this->hasColumn('is_read', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));


        $this->index('userIndex', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}