<?php

/**
 * BaseUserView
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $target_user_id
 * @property sfGuardUser $Item
 * 
 * @method integer     getTargetUserId()   Returns the current record's "target_user_id" value
 * @method sfGuardUser getItem()           Returns the current record's "Item" value
 * @method UserView    setTargetUserId()   Sets the current record's "target_user_id" value
 * @method UserView    setItem()           Sets the current record's "Item" value
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserView extends View
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('user_view');
        $this->hasColumn('target_user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));


        $this->index('targetUserindex', array(
             'fields' => 
             array(
              0 => 'target_user_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Item', array(
             'local' => 'target_user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}