<?php

/**
 * BaseUserBadge
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $num_completed
 * @property integer $level_completed
 * @property integer $user_id
 * @property integer $badge_id
 * @property sfGuardUser $User
 * @property Badge $Badge
 * 
 * @method integer     getId()              Returns the current record's "id" value
 * @method integer     getNumCompleted()    Returns the current record's "num_completed" value
 * @method integer     getLevelCompleted()  Returns the current record's "level_completed" value
 * @method integer     getUserId()          Returns the current record's "user_id" value
 * @method integer     getBadgeId()         Returns the current record's "badge_id" value
 * @method sfGuardUser getUser()            Returns the current record's "User" value
 * @method Badge       getBadge()           Returns the current record's "Badge" value
 * @method UserBadge   setId()              Sets the current record's "id" value
 * @method UserBadge   setNumCompleted()    Sets the current record's "num_completed" value
 * @method UserBadge   setLevelCompleted()  Sets the current record's "level_completed" value
 * @method UserBadge   setUserId()          Sets the current record's "user_id" value
 * @method UserBadge   setBadgeId()         Sets the current record's "badge_id" value
 * @method UserBadge   setUser()            Sets the current record's "User" value
 * @method UserBadge   setBadge()           Sets the current record's "Badge" value
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserBadge extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_badge');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('num_completed', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '',
             ));
        $this->hasColumn('level_completed', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('badge_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));


        $this->index('userIndex', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Badge', array(
             'local' => 'badge_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}