<?php

/**
 * BaseUserScores
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $count
 * @property string $source
 * @property integer $user_id
 * @property integer $rater_id
 * @property sfGuardUser $User
 * @property sfGuardUser $Rater
 * 
 * @method integer     getCount()    Returns the current record's "count" value
 * @method string      getSource()   Returns the current record's "source" value
 * @method integer     getUserId()   Returns the current record's "user_id" value
 * @method integer     getRaterId()  Returns the current record's "rater_id" value
 * @method sfGuardUser getUser()     Returns the current record's "User" value
 * @method sfGuardUser getRater()    Returns the current record's "Rater" value
 * @method UserScores  setCount()    Sets the current record's "count" value
 * @method UserScores  setSource()   Sets the current record's "source" value
 * @method UserScores  setUserId()   Sets the current record's "user_id" value
 * @method UserScores  setRaterId()  Sets the current record's "rater_id" value
 * @method UserScores  setUser()     Sets the current record's "User" value
 * @method UserScores  setRater()    Sets the current record's "Rater" value
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseUserScores extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_scores');
        $this->hasColumn('count', 'integer', 3, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '3',
             ));
        $this->hasColumn('source', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('rater_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as Rater', array(
             'local' => 'rater_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}