<?php

/**
 * BaseCommentFlags
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $comment_id
 * @property Comment $Comment
 * 
 * @method integer      getCommentId()  Returns the current record's "comment_id" value
 * @method Comment      getComment()    Returns the current record's "Comment" value
 * @method CommentFlags setCommentId()  Sets the current record's "comment_id" value
 * @method CommentFlags setComment()    Sets the current record's "Comment" value
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCommentFlags extends Flag
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('comment_flags');
        $this->hasColumn('comment_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Comment', array(
             'local' => 'comment_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}