<?php

/**
 * BaseLimelightNews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $limelight_id
 * @property integer $news_id
 * @property Limelight $Limelight
 * @property News $News
 * 
 * @method integer       getLimelightId()  Returns the current record's "limelight_id" value
 * @method integer       getNewsId()       Returns the current record's "news_id" value
 * @method Limelight     getLimelight()    Returns the current record's "Limelight" value
 * @method News          getNews()         Returns the current record's "News" value
 * @method LimelightNews setLimelightId()  Sets the current record's "limelight_id" value
 * @method LimelightNews setNewsId()       Sets the current record's "news_id" value
 * @method LimelightNews setLimelight()    Sets the current record's "Limelight" value
 * @method LimelightNews setNews()         Sets the current record's "News" value
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLimelightNews extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('limelight_news');
        $this->hasColumn('limelight_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('news_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Limelight', array(
             'local' => 'limelight_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('News', array(
             'local' => 'news_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}