<?php

/**
 * BasePlaylistSong
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $playlist_id
 * @property integer $song_id
 * @property Playlist $Playlist
 * @property Song $Song
 * 
 * @method integer      getPlaylistId()  Returns the current record's "playlist_id" value
 * @method integer      getSongId()      Returns the current record's "song_id" value
 * @method Playlist     getPlaylist()    Returns the current record's "Playlist" value
 * @method Song         getSong()        Returns the current record's "Song" value
 * @method PlaylistSong setPlaylistId()  Sets the current record's "playlist_id" value
 * @method PlaylistSong setSongId()      Sets the current record's "song_id" value
 * @method PlaylistSong setPlaylist()    Sets the current record's "Playlist" value
 * @method PlaylistSong setSong()        Sets the current record's "Song" value
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlaylistSong extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('playlist_song');
        $this->hasColumn('playlist_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('song_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Playlist', array(
             'local' => 'playlist_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Song', array(
             'local' => 'song_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}