<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryTable extends Doctrine_Table
{
  /**
   *
   * @return <array> list of categories
   * Will return an array of categories
   */
  public function getCategories()
  {
    $q = Doctrine_Query::create()
        ->select('c.*, c1.*, c2.*, c3.*')
        ->from('Category c')
        ->leftJoin('c.Children c1 WITH c1.status = ?', 'Active')
        ->leftJoin('c1.Children c2 WITH c2.status = ?', 'Active')
        ->leftJoin('c2.Children c3 WITH c3.status = ?', 'Active')
        ->where('c.status = ?', 'Active')
        ->orderBy('c.name')
        ->addOrderBy('c1.name')
        ->addOrderBy('c2.name')
        ->addOrderBy('c3.name');
    $result = $q->fetchArray();
    return $result;
  }

  // used on the backend to display the list of categories (generator.yml in category backend module)
  public function retrieveBackendCategoryList(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();

    $q->leftJoin($rootAlias . '.Parent p');

    return $q;
  }
}