<?php

/**
 * Favorite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Favorite extends BaseFavorite
{
  public function postInsert($event)
  {
    $item = $this->Item;
    $item->favorited_count += 1;
    if ($item->favorite_badge_flag == 0 && $item->favorited_count == sfConfig::get('app_badge_'.get_class($this).'_min')) {
      Doctrine::getTable('Badge')->increaseBadgeStat(sfConfig::get('app_badge_'.get_class($this).'_add'), $item->user_id);
      $item->favorite_badge_flag = 1;
    }
    $item->save();

    $cacheDriver = $this->getTable()->getAttribute(Doctrine_Core::ATTR_RESULT_CACHE);
    if (get_class($this) == 'SongFavorite')
    {
      // delete the corresponding news cache for this user
      $cacheDriver->delete('song_stats_'.$item->id.'_'.$this->user_id);
      // delete the users favorited list
      $cacheDriver->deleteByPrefix('user_'.$this->user_id.'_favorited_song');
    }
    else if (get_class($this) == 'NewsFavorite')
    {
      // delete the corresponding news cache for this user
      $cacheDriver->delete('news_stats_'.$item->id.'_'.$this->user_id);
      // delete the users favorited list
      $cacheDriver->deleteByPrefix('user_'.$this->user_id.'_favorited_news');
    }
    else if (get_class($this) == 'LimelightFavorite')
    {
      // delete the corresponding limelight cache for this user
      $cacheDriver->deleteByPrefix('limelight_stats_'.$item->id.'_'.$this->user_id);
      // delete the users favorited list
      $cacheDriver->deleteByPrefix('user_'.$this->user_id.'_favorited_limelight');
    }
  }

  public function preDelete($event)
  {
    $item = $this->Item;
    $item->favorited_count -= 1;
    $item->save();

    $cacheDriver = $this->getTable()->getAttribute(Doctrine_Core::ATTR_RESULT_CACHE);
    if (get_class($this) == 'SongFavorite')
    {
      // delete the corresponding news cache for this user
      $cacheDriver->delete('song_stats_'.$item->id.'_'.$this->user_id);
      // delete the users favorited list
      $cacheDriver->deleteByPrefix('user_'.$this->user_id.'_favorited_song');
    }
    else if (get_class($this) == 'NewsFavorite')
    {
      // delete the corresponding news cache for this user
      $cacheDriver->delete('news_stats_'.$item->id.'_'.$this->user_id);
      // delete the users favorited list
      $cacheDriver->deleteByPrefix('user_'.$this->user_id.'_favorited_news');
    }
    else if (get_class($this) == 'LimelightFavorite')
    {
      // delete the corresponding limelight cache for this user
      $cacheDriver->deleteByPrefix('limelight_'.$item->name_slug.'_'.$this->user_id);
      // delete the users favorited list
      $cacheDriver->deleteByPrefix('user_'.$this->user_id.'_favorited_limelight');
    }
  }
}