<?php

/**
 * FollowUserReference
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class FollowUserReference extends BaseFollowUserReference
{
  public function postInsert($event)
  {
    $cacheDriver = $this->getTable()->getAttribute(Doctrine_Core::ATTR_RESULT_CACHE);
    $cacheDriver->delete('user_follow_'.$this->user1_id.'_'.$this->user2_id);
    $cacheDriver->delete('user_'.$this->user1_id.'_user_following');

    Doctrine::getTable('Badge')->increaseBadgeStat('Sheep', $this->user1_id);
    Doctrine::getTable('Badge')->increaseBadgeStat('King', $this->user2_id);
  }
}