<?php

/**
 * FollowLimelightReference
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class FollowLimelightReference extends BaseFollowLimelightReference
{
  public function postInsert($event)
  {
    $cacheDriver = $this->getTable()->getAttribute(Doctrine_Core::ATTR_RESULT_CACHE);
    $cacheDriver->delete('limelight_follow_'.$this->user_id.'_'.$this->limelight_id);
    $cacheDriver->delete('user_'.$this->user_id.'_limelight_following');
  }

  public function postDelete($event)
  {
    $cacheDriver = $this->getTable()->getAttribute(Doctrine_Core::ATTR_RESULT_CACHE);
    $cacheDriver->delete('limelight_follow_'.$this->user_id.'_'.$this->limelight_id);
  }
}