<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LimelightOwn extends BaseLimelightOwn
{
  public function postInsert($event)
  {
    $limelight = $this->Item;
    $limelight->own_count++;
    $limelight->save();
  }

  public function postDelete($event)
  {
    $limelight = $this->Item;
    $limelight->own_count--;
    $limelight->save();
  }
}