<?php

/**
 * LimelightSummary
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class LimelightSummary extends BaseLimelightSummary
{
  function postInsert($event)
  {
    // set the previously active summary to inactive
    Doctrine_Query::create()
    ->update('LimelightSummary')
    ->set('is_active', '0')
    ->where('item_id = ? AND id != ? AND is_active = ?', array($this->item_id, $this->id, true))
    ->execute();

    $cacheDriver = $this->getTable()->getAttribute(Doctrine_Core::ATTR_RESULT_CACHE);
    $cacheDriver->delete('limelight_stats_'.$this->item_id);

    if (sfContext::hasInstance())
    {
      $cacheManager = sfContext::getInstance()->getViewCacheManager();
      if ($cacheManager)
        $cacheManager->remove('@sf_cache_partial?module=content&action=_feedLimelight&sf_cache_key='.$this->item_id.'*');
    }
  }
}