<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LimelightReviewUserTable extends ItemTable
{
  public function getReviews($ll_id, $user_id, $o, $section = null)
  {
    switch ($o)
    {
      case 0:
        $orderBy = 'r.created_at DESC';
        break;
      case 1:
        $orderBy = 'r.review_score DESC';
        break;
      case 2:
        $orderBy = 'p.score DESC';
        break;
      case 3:
        $orderBy = 'r.score DESC';
        break;
      case 4:
        $orderBy = 'r.score ASC';
        break;
    }

    $q = Doctrine_Query::create()
        ->select('r.*, s.id AS scored, sp.*, cst.*')
        ->from('LimelightReviewUser r')
        ->leftJoin('r.Scores s WITH s.user_id = ?', $user_id)
        ->leftJoin('r.LimelightReviewScoreParts sp')
        ->leftJoin('sp.CategoryScoreType cst')
        ->where('r.limelight_id = ? AND r.status = ?', array($ll_id, 'Active'))
        ->orderBy($orderBy);

    if ($o == 2) {
      $q->addSelect('u.id, p.score');
      $q->leftJoin('r.User u');
      $q->leftJoin('u.Profile p');
    }

    if ($section)
      $q->offset($section * sfConfig::get('app_reviews_feed_num'));

    $q->limit(sfConfig::get('app_reviews_feed_num'));

    $result = $q->fetchArray();
    return $result;
  }
}