<?php

/**
 * LimelightScore
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class LimelightScore extends BaseLimelightScore
{
  public function postInsert($event)
  {
    $item = $this->Item;

    $item->score += $this->amount;
    $item->save();

    $cacheDriver = $this->getTable()->getAttribute(Doctrine_Core::ATTR_RESULT_CACHE);
    $cacheDriver->delete('limelight_'.$item->id);
    
    $cacheManager = sfContext::getInstance()->getViewCacheManager();
      if ($cacheManager)
        $cacheManager->remove('@sf_cache_partial?module=content&action=_feedLimelight&sf_cache_key='.$item->id);

    parent::postInsert($event);
  }
}