<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NewsTag extends BaseNewsTag
{
  public function postSave($event)
  {
    $cacheDriver = $this->getTable()->getAttribute(Doctrine_Core::ATTR_RESULT_CACHE);
    $cacheDriver->delete('news_tags_'.$this->item_id);
  }
}