<?php

/**
 * NewsScore
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class NewsScore extends BaseNewsScore
{
  public function postInsert($event)
  {
    $item = $this->Item;
    
    $cacheDriver = $this->getTable()->getAttribute(Doctrine_Core::ATTR_RESULT_CACHE);
    
    $cacheDriver->delete('news_'.$item->title_slug);
    $cacheDriver->deleteByPrefix('news_stats_'.$item->id.'_'.$this->user_id);

    parent::postInsert($event);
  }
}