<?php

/**
 * NewsFlag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class NewsFlag extends BaseNewsFlag
{
  public function postSave($event)
  {
    $news_story = $this->Item;
    $cacheDriver = $this->getTable()->getAttribute(Doctrine_Core::ATTR_RESULT_CACHE);
    $cacheDriver->delete('news_stats_'.$news_story->id.'_'.$this->user_id);

    if ($news_story->status == 'Flagged')
      $cacheDriver->delete('news_'.$news_story->title_slug);
  }
}