<?php

/**
 * NewsLinkFlag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class NewsLinkFlag extends BaseNewsLinkFlag
{
  public function postSave($event)
  {
    $link = $this->Item;
    $cacheDriver = $this->getTable()->getAttribute(Doctrine_Core::ATTR_RESULT_CACHE);

    if ($link->status == 'Flagged')
      $cacheDriver->delete('news_links_'.$link->item_id);
  }
}