<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfileTable extends Doctrine_Table
{
  public function checkEmail($email)
  {
    $q = Doctrine_Query::create()
            ->from('Profile')
            ->where('email = ?', $email);
    $result = $q->execute();
    return $result[0]->email;
  }

  // reduce the user score after an item that contributed to their score is flagged
  public function reduceUserScore($item_type, $item_id, $target_user_id)
  {
    $q = Doctrine_Query::create()
        ->select('id, SUM(amount) score')
        ->from($item_type.'Score')
        ->where('item_id = ?', array($item_id));
    $result = $q->fetchOne();
    
    // only update the users score if the flagged item increased the users score
    if ($result != null && $result['score'] > 0)
    {
      $q = Doctrine_Query::create()
          ->update('Profile')
          ->set('score', 'score - ' . $result['score'])
          ->where('sf_guard_user_id = ?', $target_user_id);
      $q->execute();
      
      // flag the individual scores associated with the increase in user score
      Doctrine::getTable('UserScore')->flagScores($item_type, $item_id, $target_user_id);
    }
  }
}