<?php

/**
 * SongPlay
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SongPlay extends BaseSongPlay
{
  public function postInsert($event) {

    // increase the total plays on the song
    $item = $this->getItem();
    $item->total_plays += 1;
    $item->save();

    // increase the total plays on the limelights connected to the song
    $limelights = $item->Limelights;
    foreach ($limelights as $limelight)
    {
      $limelight->total_plays += 1;
      $limelight->save();
    }
  }
}