<?php

/**
 * UserStrike
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UserStrike extends BaseUserStrike
{
  public function postInsert($event) {
    $strikes = $this->User->Strikes;
    $count = 0;

    // check how many strikes the user currently has
    foreach ($strikes as $strike) {
      $created = strtotime($strike->created_at);
      $td = mktime(0, 0, 0, date('n'), date('j'), date('Y')) - mktime(0, 0, 0, date('n', $created), date('j', $created), date('Y', $created));
      $td = $td/24/60/60;
      if ($strike->status == 'Active' && $td <= sfConfig::get('app_user_strike_time'))
        $count++;
    }

    // if the user has exceeded the max amount of strikes at one time, suspend them and mark the strikes as used
    if ($count >= sfConfig::get('app_user_strike_min')) {
      foreach ($strikes as $strike) {
        if ($strike->status == 'Active') {
          $strike->status = 'Used';
          $strike->save();
        }
      }
      $this->User->Profile->status = 'Suspended';
      $suspend_until = time() + (sfConfig::get('app_user_suspend_until') * 24 * 60 * 60);
      $this->User->Profile->suspend_until = date('Y-m-d', $suspend_until);
      $this->User->save();
    }
  }
}