<?php

/**
 * UserScore
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UserScore extends BaseUserScore
{
  public function postInsert($event) {
    if ($this->target_user_id != null) {
      $user = $this->TargetUser;
      $user->Profile->score += $this->amount;
      $user->save();
      $user->adjustModLevels();
    }

    if ($this->user_id != null) {
      $raterProfile = $this->Rater->Profile;
      if ($this->amount < 0)
        $raterProfile->score_negative_count += 1;
      else
        $raterProfile->score_positive_count += 1;
      if ($raterProfile->score_negative_count != 0)
        $raterProfile->score_ratio = $raterProfile->score_positive_count / $raterProfile->score_negative_count;
      $this->Rater->save();
    }
  }
}