<?php

/**
 * WikiScore
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    limelight
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class WikiScore extends BaseWikiScore
{
  public function postSave($event)
  {
    $item = $this->Item;
    $cacheDriver = $this->getTable()->getAttribute(Doctrine_Core::ATTR_RESULT_CACHE);
    $cacheDriver->deleteByPrefix('wiki_history_'.$item->group_id);
    $cacheDriver->deleteByPrefix('wiki_history_active_'.$item->group_id);
  }
}