<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base {

  public function up() {
    $this->addColumn('user_revenue', 'claim_date', 'timestamp', 25);
    $this->addColumn('user_revenue', 'paypal_invoice', 'string', 255);
  }

  public function down() {
    $this->removeColumn('user_revenue', 'claim_date');
    $this->removeColumn('user_revenue', 'paypal_invoice');
  }

}