<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base {

  public function up() {
    $this->createTable('user_revenue', array(
        'id' =>
        array(
            'type' => 'integer',
            'length' => '4',
            'autoincrement' => '1',
            'primary' => '1',
        ),
        'amount' =>
        array(
            'type' => 'float',
            'length' => '',
        ),
        'popularity' =>
        array(
            'type' => 'integer',
            'length' => '4',
        ),
        'status' =>
        array(
            'type' => 'enum',
            'values' =>
            array(
                0 => 'Active',
                1 => 'Pending',
                2 => 'Flagged',
                3 => 'Struck',
                4 => 'Disabled',
            ),
            'default' => 'Active',
            'length' => '',
        ),
        'claimed' =>
        array(
            'type' => 'boolean',
            'default' => '0',
            'length' => '',
        ),
        'user_id' =>
        array(
            'type' => 'integer',
            'length' => '4',
        ),
        'created_at' =>
        array(
            'notnull' => '1',
            'type' => 'timestamp',
            'length' => '25',
        ),
        'updated_at' =>
        array(
            'notnull' => '1',
            'type' => 'timestamp',
            'length' => '25',
        ),
        'deleted_at' =>
        array(
            'default' => '',
            'notnull' => '',
            'type' => 'timestamp',
            'length' => '25',
        ),
            ), array(
        'indexes' =>
        array(
            'userIndex' =>
            array(
                'fields' =>
                array(
                    0 => 'user_id',
                ),
            ),
        ),
        'primary' =>
        array(
            0 => 'id',
        ),
    ));
  }

  public function down() {
    $this->dropTable('user_revenue');
  }

}