<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version10 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('limelight', 'module_products', 'bool');
    }

    public function down()
    {
        $this->removeColumn('limelight', 'module_products');
    }
}