<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('limelight', 'limelight_manufacturer_id_limelight_id', array(
             'name' => 'limelight_manufacturer_id_limelight_id',
             'local' => 'manufacturer_id',
             'foreign' => 'id',
             'foreignTable' => 'limelight',
             ));
        $this->addIndex('limelight', 'limelight_manufacturer_id', array(
             'fields' => 
             array(
              0 => 'manufacturer_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('limelight', 'limelight_manufacturer_id_limelight_id');
        $this->removeIndex('limelight', 'limelight_manufacturer_id', array(
             'fields' => 
             array(
              0 => 'manufacturer_id',
             ),
             ));
    }
}