<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version12 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('limelight', 'limelight_company_id_limelight_id', array(
             'name' => 'limelight_company_id_limelight_id',
             'local' => 'company_id',
             'foreign' => 'id',
             'foreignTable' => 'limelight',
             ));
        $this->addIndex('limelight', 'limelight_company_id', array(
             'fields' =>
             array(
              0 => 'company_id',
             ),
             ));

        $this->createForeignKey('limelight_slice', 'limelight_slice_user_id_sf_guard_user_id', array(
             'name' => 'limelight_slice_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('limelight_slice', 'limelight_slice_item_id_limelight_id', array(
             'name' => 'limelight_slice_item_id_limelight_id',
             'local' => 'item_id',
             'foreign' => 'id',
             'foreignTable' => 'limelight',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('limelight_slice', 'limelight_slice_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('limelight_slice', 'limelight_slice_item_id', array(
             'fields' => 
             array(
              0 => 'item_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('limelight', 'limelight_company_id_limelight_id');
        $this->removeIndex('limelight', 'limelight_company_id', array(
             'fields' =>
             array(
              0 => 'company_id',
             ),
             ));

        $this->dropForeignKey('limelight_slice', 'limelight_slice_user_id_sf_guard_user_id');
        $this->dropForeignKey('limelight_slice', 'limelight_slice_item_id_limelight_id');
        $this->removeIndex('limelight_slice', 'limelight_slice_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('limelight_slice', 'limelight_slice_item_id', array(
             'fields' => 
             array(
              0 => 'item_id',
             ),
             ));
    }
}