<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('limelight', 'own_count');
        $this->removeColumn('limelight', 'favorited_count');
        $this->removeColumn('limelight', 'pro_count');
        $this->removeColumn('limelight', 'con_count');
        $this->removeColumn('limelight', 'review_pro_count');
        $this->removeColumn('limelight', 'review_user_count');
        $this->removeColumn('limelight', 'review_pro_average');
        $this->removeColumn('limelight', 'review_user_average');
        $this->removeColumn('limelight', 'review_pro_weighted_average');
        $this->removeColumn('limelight', 'review_user_weighted_average');
        $this->removeColumn('limelight', 'mod_max');
        $this->addColumn('limelight', 'module_specifications', 'bool');
        $this->addColumn('limelight', 'module_features', 'bool');
        $this->addColumn('limelight', 'module_procon', 'bool');
        $this->changeColumn('limelight', 'limelight_type', 'enum', '', array(
             'values' => 
             array(
              0 => 'Gadget',
              1 => 'Software',
              2 => 'Technology',
              3 => 'Company',
             ),
             'default' => 'Gadget',
             ));
    }

    public function down()
    {
        $this->addColumn('limelight', 'own_count', 'integer', '4', array(
             'default' => '0',
             ));
        $this->addColumn('limelight', 'favorited_count', 'integer', '4', array(
             'default' => '0',
             ));
        $this->addColumn('limelight', 'pro_count', 'integer', '4', array(
             'default' => '0',
             ));
        $this->addColumn('limelight', 'con_count', 'integer', '4', array(
             'default' => '0',
             ));
        $this->addColumn('limelight', 'review_pro_count', 'integer', '4', array(
             'default' => '0',
             ));
        $this->addColumn('limelight', 'review_user_count', 'integer', '4', array(
             'default' => '0',
             ));
        $this->addColumn('limelight', 'review_pro_average', 'integer', '4', array(
             'default' => '0',
             ));
        $this->addColumn('limelight', 'review_user_average', 'integer', '4', array(
             'default' => '0',
             ));
        $this->addColumn('limelight', 'review_pro_weighted_average', 'integer', '4', array(
             'default' => '0',
             ));
        $this->addColumn('limelight', 'review_user_weighted_average', 'integer', '4', array(
             'default' => '0',
             ));
        $this->addColumn('limelight', 'mod_max', 'integer', '4', array(
             'default' => '3',
             ));
        $this->removeColumn('limelight', 'module_specifications');
        $this->removeColumn('limelight', 'module_features');
        $this->removeColumn('limelight', 'module_procon');
    }
}