<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('limelight', 'manufacturer');
        $this->addColumn('limelight', 'manufacturer_name', 'string', '255', array(
             ));
        $this->addColumn('limelight', 'manufacturer_id', 'integer', '4', array(
             ));
    }

    public function down()
    {
        $this->addColumn('limelight', 'manufacturer', 'string', '255', array(
             ));
        $this->removeColumn('limelight', 'manufacturer_name');
        $this->removeColumn('limelight', 'manufacturer_id');
    }
}