<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version14 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('limelight_review_pro', 'limelight_review_pro_source_id_limelight_id', array(
             'name' => 'limelight_review_pro_source_id_limelight_id',
             'local' => 'source_id',
             'foreign' => 'id',
             'foreignTable' => 'limelight',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('limelight_specification', 'limelight_specification_source_id_limelight_id', array(
             'name' => 'limelight_specification_source_id_limelight_id',
             'local' => 'source_id',
             'foreign' => 'id',
             'foreignTable' => 'limelight',
             ));
        $this->createForeignKey('news_link', 'news_link_source_id_limelight_id', array(
             'name' => 'news_link_source_id_limelight_id',
             'local' => 'source_id',
             'foreign' => 'id',
             'foreignTable' => 'limelight',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('source_view', 'source_view_item_id_limelight_id', array(
             'name' => 'source_view_item_id_limelight_id',
             'local' => 'item_id',
             'foreign' => 'id',
             'foreignTable' => 'limelight',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('limelight_review_pro', 'limelight_review_pro_source_id', array(
             'fields' => 
             array(
              0 => 'source_id',
             ),
             ));
        $this->addIndex('limelight_specification', 'limelight_specification_source_id', array(
             'fields' => 
             array(
              0 => 'source_id',
             ),
             ));
        $this->addIndex('news_link', 'news_link_source_id', array(
             'fields' => 
             array(
              0 => 'source_id',
             ),
             ));
        $this->addIndex('source_view', 'source_view_item_id', array(
             'fields' => 
             array(
              0 => 'item_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('limelight_review_pro', 'limelight_review_pro_source_id_limelight_id');
        $this->dropForeignKey('limelight_specification', 'limelight_specification_source_id_limelight_id');
        $this->dropForeignKey('news_link', 'news_link_source_id_limelight_id');
        $this->dropForeignKey('source_view', 'source_view_item_id_limelight_id');
        $this->removeIndex('limelight_review_pro', 'limelight_review_pro_source_id', array(
             'fields' => 
             array(
              0 => 'source_id',
             ),
             ));
        $this->removeIndex('limelight_specification', 'limelight_specification_source_id', array(
             'fields' => 
             array(
              0 => 'source_id',
             ),
             ));
        $this->removeIndex('news_link', 'news_link_source_id', array(
             'fields' => 
             array(
              0 => 'source_id',
             ),
             ));
        $this->removeIndex('source_view', 'source_view_item_id', array(
             'fields' => 
             array(
              0 => 'item_id',
             ),
             ));
    }
}